python train_controlnet.py \
 --pretrained_model_name_or_path "runwayml/stable-diffusion-v1-5" \
 --controlnet_model_name_or_path "ControlNet-1-1-preview/control_v11p_sd15_lineart" \
 --output_dir="./out_facade_lines" \
 --train_data_dir='/research/GDA/xuningli/cross-view/ground_view_generation/data' \
 --conditioning_image_column="condition" \
 --caption_column="text" \
 --lora_path='/research/GDA/xuningli/cross-view/ground_view_generation/outputs/jax_7868_pano_lora/checkpoint-70000' \
 --resolution=512 \
 --validation_image "/research/GDA/xuningli/cross-view/ground_view_generation/data/experiment/train/facade_lines/JAX_068 82_lines.png" "/research/GDA/xuningli/cross-view/ground_view_generation/data/experiment/train/facade_lines/JAX_214 5_lines.png" "/research/GDA/xuningli/cross-view/ground_view_generation/data/experiment/train/facade_lines/JAX_171 71_lines.png" \
 --validation_prompt "street-view, panorama image, high resolution" \
 --train_batch_size=4 \
 --max_train_steps=60001 \
 --tracker_project_name="controlnet-facade-lines" \
 --enable_xformers_memory_efficient_attention \
 --checkpointing_steps=5000 \
 --validation_steps=200 \
 --report_to wandb